CREATE TABLE IF NOT EXISTS routes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  theme_id BIGINT,
  city VARCHAR(64),
  start_lat DECIMAL(10,7),
  start_lng DECIMAL(10,7),
  end_lat DECIMAL(10,7),
  end_lng DECIMAL(10,7),
  total_distance INT COMMENT '米',
  duration INT COMMENT '分钟',
  difficulty TINYINT COMMENT '1:简单 2:中等 3:困难',
  cover_image VARCHAR(255),
  created_by BIGINT NOT NULL,
  status TINYINT DEFAULT 0 COMMENT '0:草稿 1:待审 2:已发布 3:已下架',
  favorite_count INT DEFAULT 0,
  rating DECIMAL(2,1) DEFAULT 0,
  rating_count INT DEFAULT 0,
  view_count INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME,
  INDEX idx_status (status),
  INDEX idx_city (city),
  INDEX idx_theme (theme_id),
  INDEX idx_created_by (created_by),
  INDEX idx_rating (rating),
  INDEX idx_created_at (created_at),
  CONSTRAINT fk_routes_theme FOREIGN KEY (theme_id) REFERENCES themes(id) ON DELETE SET NULL,
  CONSTRAINT fk_routes_user FOREIGN KEY (created_by) REFERENCES users(id)
);
