CREATE TABLE IF NOT EXISTS landmarks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  address VARCHAR(255),
  lat DECIMAL(10,7) NOT NULL,
  lng DECIMAL(10,7) NOT NULL,
  category_id BIGINT,
  description TEXT,
  cover_image VARCHAR(255),
  created_by BIGINT NOT NULL,
  status TINYINT DEFAULT 0 COMMENT '0:待审 1:已发布',
  rating DECIMAL(2,1) DEFAULT 0,
  rating_count INT DEFAULT 0,
  view_count INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME,
  INDEX idx_status (status),
  INDEX idx_category (category_id),
  INDEX idx_created_by (created_by),
  INDEX idx_rating (rating),
  INDEX idx_lat_lng (lat, lng),
  CONSTRAINT fk_landmarks_category FOREIGN KEY (category_id) REFERENCES landmark_categories(id) ON DELETE SET NULL,
  CONSTRAINT fk_landmarks_user FOREIGN KEY (created_by) REFERENCES users(id)
);
