CREATE TABLE IF NOT EXISTS events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  route_id BIGINT,
  meetup_address VARCHAR(255),
  meetup_lat DECIMAL(10,7),
  meetup_lng DECIMAL(10,7),
  meetup_time DATETIME NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  max_participants INT DEFAULT 20,
  current_participants INT DEFAULT 0,
  fee INT DEFAULT 0 COMMENT '费用(分)',
  description TEXT,
  created_by BIGINT NOT NULL,
  status TINYINT DEFAULT 0 COMMENT '0:待开始 1:进行中 2:已结束 3:已取消',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_status (status),
  INDEX idx_meetup_time (meetup_time),
  INDEX idx_created_by (created_by),
  CONSTRAINT fk_events_route FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE SET NULL,
  CONSTRAINT fk_events_user FOREIGN KEY (created_by) REFERENCES users(id)
);
