FROM --platform=$BUILDPLATFORM golang:1.22-bookworm AS build
WORKDIR /src
ARG TARGETOS
ARG TARGETARCH
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -buildvcs=false -o /out/citywalk ./cmd/api

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=build /out/citywalk /app/citywalk
COPY migrations /app/migrations
EXPOSE 8080
CMD ["/app/citywalk"]
